name: Build macOS DMG

on:
  push:
    tags:
      - '*'  # Run only when a tag is pushed

# Add permissions block to explicitly grant release creation permission
permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Get tag version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 pyinstaller
        brew install create-dmg imagemagick
    
    - name: Create app icon
      run: |
        # Create a simple icon file using a different approach
        echo "Creating app icon..."
        
        # Create a simple colored square with text
        mkdir -p icons.iconset
        
        # Create a base PNG with a blue background
        convert -size 1024x1024 xc:#0078D4 -fill white -gravity center -pointsize 512 -annotate 0 "TW" base_icon.png
        
        # Create different sizes for the iconset
        for size in 16 32 64 128 256 512; do
          convert base_icon.png -resize ${size}x${size} icons.iconset/icon_${size}x${size}.png
          convert base_icon.png -resize $((size*2))x$((size*2)) icons.iconset/icon_${size}x${size}@2x.png
        done
        
        # Convert the iconset to icns
        iconutil -c icns icons.iconset -o app_icon.icns
        
        # Verify the icon was created
        ls -la app_icon.icns
    
    - name: Build application with PyInstaller
      run: |
        # Update version in app
        VERSION_PY="version.py"
        echo "VERSION = '${VERSION}'" > $VERSION_PY
        
        # Build a macOS app bundle
        pyinstaller --name="MSTeamsWaker" \
          --windowed \
          --icon=app_icon.icns \
          --add-data="README.md:." \
          --add-data="${VERSION_PY}:." \
          --osx-bundle-identifier="com.msteamswaker.app" \
          teams_waker_app.py
        
        # Debug output
        ls -la dist/
    
    - name: Create DMG using create-dmg
      run: |
        # Create DMG with proper layout
        DMG_NAME="MSTeamsWaker-${VERSION}.dmg"
        
        create-dmg \
          --volname "MS Teams Waker ${VERSION}" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "MSTeamsWaker.app" 200 190 \
          --hide-extension "MSTeamsWaker.app" \
          --app-drop-link 600 185 \
          "$DMG_NAME" \
          "dist/MSTeamsWaker.app"
    
    - name: Upload DMG artifact
      uses: actions/upload-artifact@v4
      with:
        name: MSTeamsWaker-${{ env.VERSION }}
        path: MSTeamsWaker-${{ env.VERSION }}.dmg
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: MSTeamsWaker-${{ env.VERSION }}.dmg
