name: Build macOS DMG

on:
  push:
    tags:
      - '*'  # Run only when a tag is pushed

# Add permissions block to explicitly grant release creation permission
permissions:
  contents: write

jobs:
  build:
    runs-on: macos-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Get tag version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 pyinstaller
        brew install create-dmg
    
    - name: Create app icon
      run: |
        # Create a placeholder icon if none exists
        if [ ! -f app_icon.png ]; then
          # Create a simple icon using macOS tools
          echo '
          tell application "System Events"
              set theFile to (path to temporary items as string) & "app_icon.png"
              tell application "Preview"
                  activate
                  make new document with properties {width:1024, height:1024}
                  set background color to {0, 120, 212}
                  set font color to {255, 255, 255}
                  set font name to "Arial"
                  set font size to 512
                  set text to "TW"
                  set position to {512, 512}
                  save in theFile
                  quit
              end tell
          end tell
          ' > create_icon.applescript
          
          # Use a simple circle with text
          sips -s format png -z 1024 1024 app_icon.png --out app_icon.png || true
        fi
    
    - name: Build application with PyInstaller
      run: |
        # Update version in app
        VERSION_PY="version.py"
        echo "VERSION = '${VERSION}'" > $VERSION_PY
        
        # Build a macOS app bundle
        pyinstaller --name="MSTeamsWaker" \
          --windowed \
          --icon=app_icon.png \
          --add-data="README.md:." \
          --add-data="${VERSION_PY}:." \
          --osx-bundle-identifier="com.msteamswaker.app" \
          teams_waker_app.py
        
        # Debug output
        ls -la dist/
    
    - name: Create DMG using create-dmg
      run: |
        # Create DMG with proper layout
        DMG_NAME="MSTeamsWaker-${VERSION}.dmg"
        
        create-dmg \
          --volname "MS Teams Waker ${VERSION}" \
          --volicon "app_icon.png" \
          --window-pos 200 120 \
          --window-size 800 400 \
          --icon-size 100 \
          --icon "MSTeamsWaker.app" 200 190 \
          --hide-extension "MSTeamsWaker.app" \
          --app-drop-link 600 185 \
          "$DMG_NAME" \
          "dist/MSTeamsWaker.app"
    
    - name: Upload DMG artifact
      uses: actions/upload-artifact@v4
      with:
        name: MSTeamsWaker-${{ env.VERSION }}
        path: MSTeamsWaker-${{ env.VERSION }}.dmg
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: MSTeamsWaker-${{ env.VERSION }}.dmg
