name: Build macOS DMG

on:
  push:
    tags:
      - '*'  # Run only when a tag is pushed

# Add permissions block to explicitly grant release creation permission
permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Get tag version
      id: get_version
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.9'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install PyQt5 pyinstaller dmgbuild
        sudo apt-get update
        sudo apt-get install -y imagemagick
    
    - name: Create app icon
      run: |
        # Create a placeholder icon if none exists
        if [ ! -f app_icon.png ]; then
          convert -size 1024x1024 xc:none -fill "#0078d4" -draw "circle 512,512 512,256" -pointsize 512 -font Arial -gravity center -fill white -annotate 0 "TW" app_icon.png
        fi
    
    - name: Build application with PyInstaller
      run: |
        # Update version in app
        VERSION_PY="version.py"
        echo "VERSION = '${VERSION}'" > $VERSION_PY
        
        # Build a single-file executable
        pyinstaller --name="MSTeamsWaker" \
          --onefile \
          --add-data="README.md:." \
          --add-data="${VERSION_PY}:." \
          teams_waker_app.py
        
        # Debug output
        ls -la dist/
    
    - name: Create macOS app structure
      run: |
        # Create a directory structure for the app
        mkdir -p dmg_contents/MSTeamsWaker.app/Contents/MacOS
        mkdir -p dmg_contents/MSTeamsWaker.app/Contents/Resources
        
        # Copy the executable to the .app structure
        cp dist/MSTeamsWaker dmg_contents/MSTeamsWaker.app/Contents/MacOS/
        chmod +x dmg_contents/MSTeamsWaker.app/Contents/MacOS/MSTeamsWaker
        
        # Create Info.plist
        cat > dmg_contents/MSTeamsWaker.app/Contents/Info.plist << EOF
        <?xml version="1.0" encoding="UTF-8"?>
        <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
        <plist version="1.0">
        <dict>
            <key>CFBundleExecutable</key>
            <string>MSTeamsWaker</string>
            <key>CFBundleIconFile</key>
            <string>AppIcon</string>
            <key>CFBundleIdentifier</key>
            <string>com.msteamswaker.app</string>
            <key>CFBundleInfoDictionaryVersion</key>
            <string>6.0</string>
            <key>CFBundleName</key>
            <string>MSTeamsWaker</string>
            <key>CFBundlePackageType</key>
            <string>APPL</string>
            <key>CFBundleShortVersionString</key>
            <string>${VERSION}</string>
            <key>CFBundleVersion</key>
            <string>${VERSION}</string>
            <key>LSMinimumSystemVersion</key>
            <string>10.13</string>
            <key>NSHighResolutionCapable</key>
            <true/>
        </dict>
        </plist>
        EOF
        
        # Copy icon if it exists
        if [ -f app_icon.png ]; then
          cp app_icon.png dmg_contents/MSTeamsWaker.app/Contents/Resources/AppIcon.icns
        fi
    
    - name: Create DMG using dmgbuild
      run: |
        # Create a background image
        convert -size 800x500 gradient:blue-black -font Arial -pointsize 36 -fill white -gravity center -annotate 0 "MS Teams Waker ${VERSION}\nDrag to Applications folder to install" background.png
        
        # Create dmgbuild settings file
        cat > dmgbuild_settings.py << EOF
        # -*- coding: utf-8 -*-
        from __future__ import unicode_literals
        
        import os.path
        
        # Volume format (see hdiutil create -help)
        format = defines.get('format', 'UDBZ')
        
        # Volume size
        size = defines.get('size', '100M')
        
        # Files to include
        files = ['dmg_contents/MSTeamsWaker.app']
        
        # Symlinks to create
        symlinks = {'Applications': '/Applications'}
        
        # Volume icon
        #badge_icon = 'app_icon.png'
        
        # Volume name
        volume_name = 'MS Teams Waker ${VERSION}'
        
        # Volume background
        background = 'background.png'
        
        # Window configuration
        window_rect = ((100, 100), (640, 480))
        
        # Icon locations
        icon_locations = {
            'MSTeamsWaker.app': (140, 240),
            'Applications': (500, 240)
        }
        
        # Icon size
        icon_size = 80
        
        # Text size
        text_size = 12
        
        # Window position in ((x, y), (w, h)) format
        window_rect = ((100, 100), (640, 480))
        
        # Background positioning
        background_position = 'center'
        
        # Show status bar
        show_status_bar = False
        
        # Show icon preview
        show_icon_preview = False
        
        # Show item info
        show_item_info = False
        
        # Use drop shadow
        use_drop_shadow = True
        EOF
        
        # Create DMG
        DMG_NAME="MSTeamsWaker-${VERSION}.dmg"
        dmgbuild -s dmgbuild_settings.py "MS Teams Waker ${VERSION}" "$DMG_NAME"
    
    - name: Upload DMG artifact
      uses: actions/upload-artifact@v4
      with:
        name: MSTeamsWaker-${{ env.VERSION }}
        path: MSTeamsWaker-${{ env.VERSION }}.dmg
        
    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        files: MSTeamsWaker-${{ env.VERSION }}.dmg
